//Brewers association ignore list - breweries that are duplicated or are no longer open
baIgnoreList['CA'] = [
    "21st Amendment Brewery Cafe",
    "Alvarado Street Brewery & Grill",
    "Amplified Ale Works Miramar Studio",
    "Anheuser-Busch Inc – Fairfield", /* I only recognize the one true Anheuser-Busch */
    "Anheuser-Busch Inc - Los Angeles", /* I only recognize the one true Anheuser-Busch */
    "Ballast Point Brewing Co / Home Brew Mart",
    "Ballast Point Brewing Company",
    "Ballast Point Brewing Company",
    "Ballast Point Brewing Company",
    "Ballast Point Brewing Company - Little Italy",
    "Ballast Point San Francisco",
    "Barrel Brothers Brewing Company, LLC",
    "Beachwood Blendery",
    "Beachwood Brewing",
    "Bear Republic Brewing Co - Production facility",
    "Bear Republic Brewing Co Pub & Restaurant - Lakeside",
    "Belching Beaver Brewery Tavern & Grill",
    "Belching Beaver Brewery Vista",
    "BJs Restaurant & Brewery - West Covina",
    "Bootleggers Brewery",
    "Bootlegger's Brewery Costa Mesa",
    "Bootlegger's Brewery Redlands",
    "Border X",
    "Border X Logan",
    "Brew Rebellion",
    "BrewBakers",
    "Burnin Daylight Brewing Company",
    "Central Coast Brewing Co - Higuera St.",
    "Coronado Brewing Co - Production Facility",
    "Coronado Brewing Company Imperial Beach",
    "E.J. Phair Brewing Co.",
    "Eel River Brewing Co - Facility and Warehouse",
    "FiftyFifty Brewing Production Facility",
    "Figueroa Mountain Brewing - Arroyo Grande",
    "Figueroa Mountain Brewing - Santa Barbara",
    "Figueroa Mountain Brewing - Westlake Village",
    "Firestone Walker Barrelworks",
    "Firestone Walker Brewing Co",
    "Fort Point Beer",
    "Golden Road Brewing",
    "Golden Road Brewing",
    "Golden State Brew and Grill",
    "Gordon Biersch Brewery Restaurant - Burbank",
    "Gordon Biersch Brewery Restaurant - San Diego",
    "Highland Park Brewery",
    "Hoi Polloi Brewing - Production Facility",
    "Hollister Brewing Company",
    "Karl Strauss Brewing Co",
    "Karl Strauss Brewing Co - Sorrento Mesa",
    "Karl Strauss Brewing Co - 4S Ranch",
    "Karl Strauss Brewing Co - Anaheim",
    "Karl Strauss Brewing Co - Carlsbad",
    "Karl Strauss Brewing Co - Costa Mesa",
    "Karl Strauss Brewing Co - Downtown",
    "Karl Strauss Brewing Co - Downtown Los Angeles",
    "Karl Strauss Brewing Co - La Jolla",
    "Karl Strauss Brewing Co - Universal CityWalk",
    "Kern River Brewing Company Back Yard",
    "Left Coast Brewing Co. Tasting Room Smokehouse Distillery",
    "Lost Coast Brewery and Cafe - Table Bluff Brewing, Inc.",
    "Mare Island Brewing Co. - Coal Shed Brewery",
    "Mike Hess Brewing - Miramar",
    "Modern Times - The Dankness Dojo",
    "Modern Times Barrel House",
    "Moonraker Brewing Company (Production Facility)",
    "Oggis Pizza & Brewing Co - Mission Valley",
    "Oggi's Sports Brewhouse Pizza - Apple Valley",
    "Ol' Republic Brewery Rancho Cordova",
    "Old Hangtown Beer Works",
    "Pizza Port - Bressi Ranch",
    "Pizza Port Ocean Beach",
    "Pizza Port San Clemente",
    "Pizza Port Solana Beach",
    "Riley's Brew Pub",
    "Rip Current Brewing North Park",
    "Rock Bottom Brewery - Long Beach",
    "Rock Bottom Brewery - San Jose",
    "Ruhstaller Beer",
    "Russian River Brewing",
    "Russian River Brewing Co - Production",
    "SLO Brewing Co - The Rock",
    "Smog City Brewing Wood Cellar",
    "Solvang Brewing Company - Lompoc",
    "Stadium Pizza Main ST",
    "Stone Brewing Napa",
    "Stone Brewing World Bistro & Gardens- Liberty Station",
    "Tahoe Mountain Brewing Company",
    "TAPS Brewery and Barrel Room",
    "TAPS Fish House and Brewery - Corona",
    "Temescal Brewing",
    "Track 7 Brewing Co - Natomas",
    "Unsung Brewing Company- Taproom",
    "Woods Bar & Brewery"
]

// Google sheet ignore list - breweries that are no longer open
gsIgnoreList['CA'] = [

]